Fixed hook

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,20 +1,19 @@
 #!/bin/sh
 
 echo "Testing compilation"
-ret=$(make compile-test)
-if $ret;
+if ! make compile-test;
 then
 	echo "ERROR: Code must compile with no errors. Run \`make compile-test\` to see what's wrong."
 	exit 1
 fi
 
 echo "Testing norminette"
-test=$(norminette src inc | grep Error)
+test=$(norminette | grep Error)
 if [ "$test" != "" ]
 then
-	echo "ERROR: Norminette failed. Run \`norminette src inc | grep Error` to see what's wrong."
+	echo "ERROR: Norminette failed. Run \`norminette | grep Error\` to see what's wrong."
 	exit 1
 fi
 
 echo "All OK"
-exit 1
+exit 0
